### ISSUE TITLE
not working on Sonos speakers

### ISSUE THREAD

**Issue by JPe2** [bvdbos/com.sasteren.radio#2]
Via the Audio-Jack, I can play the Radio stations, but when I choose one of my Sonos speakers, the chosen sound is not directed to that speaker, when that speaker was already playing some music, the music is not replaced by the "new radio station" sound. Using the "stop" / "Play" icons, the sound of the chosen Sonos speaker is stopping and starting again, but the source is not changing.

A second problem is that the station name does not update in the "Music" tab, after changing it in the "Settings/Radio" tab.

**Comment by bvdbos** [comment]
First problem is due to the UPNP-part of Homey, can't do anything about that. Will look into the second issue...

**Comment by bvdbos** [comment]
Afaik this works now with the latest SONOS-app?

**Comment by bvdbos** [comment]
then this might be closed?

**Comment by JPe2** [comment]
Radio App works for me, thanks.
