### ISSUE TITLE
Radio not working

### ISSUE THREAD

**Issue by egorissen** [bvdbos/com.sasteren.radio#5]
Does not work in v2.
What can i do?

Thanks,
Erik.

**Comment by Vilis007** [comment]
Please make it work in v2.
Thank you.

**Comment by bvdbos** [comment]
Guess you are talking about experimental Homey Firmware 2.0.2? There's a new app in the store now which should fix that...

**Comment by Vilis007** [comment]
Hi, I got installed radio app but I can’t use it in flow

**Comment by bvdbos** [comment]
![afbeelding](https://user-images.githubusercontent.com/1064079/52015520-75425100-24e2-11e9-8194-ee0fc0b135fb.png)

**Comment by bvdbos** [comment]
![afbeelding](https://user-images.githubusercontent.com/1064079/52015593-a28eff00-24e2-11e9-8511-48ba749b6705.png)
